### ISSUE TITLE
16bit app on /release

### ISSUE THREAD

**Issue by Shikitsuna** [v613/toonily-dl#3]
I just tested the 0.1.1 on /release and found out windows version is unsupported 16 bit app and has no .exe in it
also false negative on auto windows defender antivirus

**Comment by v613** [comment]
Hello @Shikitsuna, thank you for bringing the mistake on the Windows platform to my attention. I have fixed the issue and update the latest release and would appreciate if you could verify it one more time to ensure everything is working correctly now.


Thank you for your help in improving this product.

**Comment by Shikitsuna** [comment]
![image](https://github.com/v613/toonily-dl/assets/32604156/a730309e-0070-48d5-af2b-caaa84d4f84d)
The 16 bit error still persist both on i386 and amd64, i'm using on WinServer2019/ECPY7710 and tested same on Win 10 Pro

**Comment by v613** [comment]
Does previous version have this problem ?

**Comment by Shikitsuna** [comment]
on the first version ([v0.1.0](https://github.com/v613/toonily-dl/releases/tag/v0.1.0)) doesn't have this problem, only happened on lastesr release

**Comment by v613** [comment]
Ok thanks. I reproduce and found the problem. Work on it...

**Comment by v613** [comment]
@Shikitsuna please download release `v0.1.1` one more time.

Fixed in [commit 022d81a](https://github.com/v613/toonily-dl/commit/022d81ad0be3ac77146412d7e5944ab1096d7698)

**Comment by Shikitsuna** [comment]
The Issues with 16-bit Application on WIndows Solved/Worked Now
